require('base.core')
require('base.plugins')
require('base.keymap')
require('base.misc')

require('base.lsp')
require('base.nvim-cmp')

require('plugins.telescope')
require('plugins.treesitter')
require('plugins.vim-test')
require('plugins.git')
require('plugins.harpoon')
require('plugins.undotree')

require('custom.ruby')
require('custom.go')
require('custom.lsp')
require('custom.utils')
require('custom.experiments')
require('custom.codeowners')
