require('base.core')
require('base.plugins')
require('base.settings')
require('base.keymap')

require('plugins.telescope')
require('plugins.treesitter')
require('plugins.vim-test')
require('plugins.git')
require('plugins.harpoon')
require('plugins.undotree')

require('base.lsp')
require('base.nvim-cmp')

require('custom.experiments')
require('custom.bundle-outdated')
require('custom.packwerk-check')
require('custom.ruby')
require('custom.go')
require('custom.keymap')
