vim.keymap.set("n", "<localleader>x", '<cmd>lua DbMigrate()<CR>')
vim.keymap.set("n", "<localleader>c", '<cmd>lua BundleInstall()<CR>')
vim.keymap.set("n", "<localleader>j", '<cmd>lua AltRubyFile()<CR>')
vim.keymap.set("n", "<localleader>m", '<cmd>lua PackwerkPackageFile()<CR>')
vim.keymap.set("n", "<leader>xp", "<cmd>lua PackwerkCheck()<CR>")
vim.keymap.set("n", "<leader>ro", "<cmd>lua BundleOutdated()<CR>")
vim.keymap.set("n", "<leader>fo", "<cmd>lua FindFileOwner()<CR>")
vim.keymap.set("n", "<leader>fi", "<cmd>lua FileInfo()<CR>")
